import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./(component)/Nav";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ticket App",
  description: "Generated by sam coder",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen max-h-screen bg-slate-500 text-white">  
        <Nav />
        <div className="flex-grow overflow-y-auto bg-gray-700 text-white">
         {children}
        </div>

        </div>
        </body>
    </html>
  );
}
